<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosWifi\Entity\Device'                => __DIR__ . '/src/LosWifi/Entity/Device.php',
    'LosWifi\Entity\Site'                  => __DIR__ . '/src/LosWifi/Entity/Site.php',
    'LosWifi\Entity\Sta'                   => __DIR__ . '/src/LosWifi/Entity/Sta.php',
    'LosWifi\Module'                       => __DIR__ . '/src/LosWifi/Module.php',
    'LosWifi\Options\ModuleOptions'        => __DIR__ . '/src/LosWifi/Options/ModuleOptions.php',
    'LosWifi\Options\ModuleOptionsFactory' => __DIR__ . '/src/LosWifi/Options/ModuleOptionsFactory.php',
    'LosWifi\Service\ClientFactory'        => __DIR__ . '/src/LosWifi/Service/ClientFactory.php',
    'LosWifi\Service\UnifiClient'          => __DIR__ . '/src/LosWifi/Service/UnifiClient.php',
);
